### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Apneas** [CanineGray/Grays-CASM-mobs#1]
I am absolutely overjoyed to find this datapack, especially since I am unable to use Genetic Animals on 1.18. This is absolutely amazing in every way. Thank you! 

I AM having a bit of a texture issue on a couple mobs with a some places having see-through textures. The cows also seem to be lacking random textures, but I haven't seen too many on my server yet. I am having the issue with and without shaders and other texture packs. Is there something else I can try or is this a known issue? Thanks again for your hard work! I'm so excited to see how this develops.

I am currently using this on 1.18.1 on top of Medieval Minecraft.

![2022-03-28_00 45 59](https://user-images.githubusercontent.com/26101099/160341360-3fd48d0d-2b4e-4913-b2b4-2cf7b1b3c3ae.png)
![2022-03-28_00 46 17](https://user-images.githubusercontent.com/26101099/160341368-a293781f-d0bb-4c7c-89bf-8f47475e7c9d.png)

**Comment by CanineGray** [comment]
Thanks for enjoying the pack!
Sorry this took so long to get back to you (my life's been hectic lately).

On the see through texture issues, I'm pretty certain it's a shaders bug where transparent pixels don't register properly, I've noticed this mostly on horses patterns. It may also be just a misaligned or missing texture that managed to slip by me. If you give examples of the mobs I can look into it further.

As for the randomized mobs, they should be working fine, and you're just unlucky. The only thing I could think is I messed up the properties code that doesn't randomize them, but in that case I just updated the pack so it should hopefully be fixed in the new version.
